# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake

# The command to remove a file.
RM = /nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vsh/src/reki

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vsh/src/reki

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/rsmnaiy0zj0g4rys9n7yavzr9l0d36kn-cmake-3.30.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vsh/src/reki/CMakeFiles /home/vsh/src/reki//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vsh/src/reki/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reki

# Build rule for target.
reki: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reki
.PHONY : reki

# fast build rule for target.
reki/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/build
.PHONY : reki/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/CMakeFiles/check.dir/build.make deps/soci/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named soci_core

# Build rule for target.
soci_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_core
.PHONY : soci_core

# fast build rule for target.
soci_core/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/core/CMakeFiles/soci_core.dir/build.make deps/soci/src/core/CMakeFiles/soci_core.dir/build
.PHONY : soci_core/fast

#=============================================================================
# Target rules for targets named soci_core_static

# Build rule for target.
soci_core_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_core_static
.PHONY : soci_core_static

# fast build rule for target.
soci_core_static/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/core/CMakeFiles/soci_core_static.dir/build.make deps/soci/src/core/CMakeFiles/soci_core_static.dir/build
.PHONY : soci_core_static/fast

#=============================================================================
# Target rules for targets named soci_empty

# Build rule for target.
soci_empty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_empty
.PHONY : soci_empty

# fast build rule for target.
soci_empty/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/backends/empty/CMakeFiles/soci_empty.dir/build.make deps/soci/src/backends/empty/CMakeFiles/soci_empty.dir/build
.PHONY : soci_empty/fast

#=============================================================================
# Target rules for targets named soci_empty_static

# Build rule for target.
soci_empty_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_empty_static
.PHONY : soci_empty_static

# fast build rule for target.
soci_empty_static/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/backends/empty/CMakeFiles/soci_empty_static.dir/build.make deps/soci/src/backends/empty/CMakeFiles/soci_empty_static.dir/build
.PHONY : soci_empty_static/fast

#=============================================================================
# Target rules for targets named soci_sqlite3

# Build rule for target.
soci_sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_sqlite3
.PHONY : soci_sqlite3

# fast build rule for target.
soci_sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/backends/sqlite3/CMakeFiles/soci_sqlite3.dir/build.make deps/soci/src/backends/sqlite3/CMakeFiles/soci_sqlite3.dir/build
.PHONY : soci_sqlite3/fast

#=============================================================================
# Target rules for targets named soci_sqlite3_static

# Build rule for target.
soci_sqlite3_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_sqlite3_static
.PHONY : soci_sqlite3_static

# fast build rule for target.
soci_sqlite3_static/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/src/backends/sqlite3/CMakeFiles/soci_sqlite3_static.dir/build.make deps/soci/src/backends/sqlite3/CMakeFiles/soci_sqlite3_static.dir/build
.PHONY : soci_sqlite3_static/fast

#=============================================================================
# Target rules for targets named soci_empty_test

# Build rule for target.
soci_empty_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_empty_test
.PHONY : soci_empty_test

# fast build rule for target.
soci_empty_test/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/tests/empty/CMakeFiles/soci_empty_test.dir/build.make deps/soci/tests/empty/CMakeFiles/soci_empty_test.dir/build
.PHONY : soci_empty_test/fast

#=============================================================================
# Target rules for targets named soci_empty_test_static

# Build rule for target.
soci_empty_test_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_empty_test_static
.PHONY : soci_empty_test_static

# fast build rule for target.
soci_empty_test_static/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/tests/empty/CMakeFiles/soci_empty_test_static.dir/build.make deps/soci/tests/empty/CMakeFiles/soci_empty_test_static.dir/build
.PHONY : soci_empty_test_static/fast

#=============================================================================
# Target rules for targets named soci_sqlite3_test

# Build rule for target.
soci_sqlite3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_sqlite3_test
.PHONY : soci_sqlite3_test

# fast build rule for target.
soci_sqlite3_test/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/tests/sqlite3/CMakeFiles/soci_sqlite3_test.dir/build.make deps/soci/tests/sqlite3/CMakeFiles/soci_sqlite3_test.dir/build
.PHONY : soci_sqlite3_test/fast

#=============================================================================
# Target rules for targets named soci_sqlite3_test_static

# Build rule for target.
soci_sqlite3_test_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soci_sqlite3_test_static
.PHONY : soci_sqlite3_test_static

# fast build rule for target.
soci_sqlite3_test_static/fast:
	$(MAKE) $(MAKESILENT) -f deps/soci/tests/sqlite3/CMakeFiles/soci_sqlite3_test_static.dir/build.make deps/soci/tests/sqlite3/CMakeFiles/soci_sqlite3_test_static.dir/build
.PHONY : soci_sqlite3_test_static/fast

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/packet.o: src/packet.cc.o
.PHONY : src/packet.o

# target to build an object file
src/packet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet.cc.o
.PHONY : src/packet.cc.o

src/packet.i: src/packet.cc.i
.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet.cc.i
.PHONY : src/packet.cc.i

src/packet.s: src/packet.cc.s
.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet.cc.s
.PHONY : src/packet.cc.s

src/packet_stream.o: src/packet_stream.cc.o
.PHONY : src/packet_stream.o

# target to build an object file
src/packet_stream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet_stream.cc.o
.PHONY : src/packet_stream.cc.o

src/packet_stream.i: src/packet_stream.cc.i
.PHONY : src/packet_stream.i

# target to preprocess a source file
src/packet_stream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet_stream.cc.i
.PHONY : src/packet_stream.cc.i

src/packet_stream.s: src/packet_stream.cc.s
.PHONY : src/packet_stream.s

# target to generate assembly for a file
src/packet_stream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/packet_stream.cc.s
.PHONY : src/packet_stream.cc.s

src/protocols/arp.o: src/protocols/arp.cc.o
.PHONY : src/protocols/arp.o

# target to build an object file
src/protocols/arp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/arp.cc.o
.PHONY : src/protocols/arp.cc.o

src/protocols/arp.i: src/protocols/arp.cc.i
.PHONY : src/protocols/arp.i

# target to preprocess a source file
src/protocols/arp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/arp.cc.i
.PHONY : src/protocols/arp.cc.i

src/protocols/arp.s: src/protocols/arp.cc.s
.PHONY : src/protocols/arp.s

# target to generate assembly for a file
src/protocols/arp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/arp.cc.s
.PHONY : src/protocols/arp.cc.s

src/protocols/ethernet.o: src/protocols/ethernet.cc.o
.PHONY : src/protocols/ethernet.o

# target to build an object file
src/protocols/ethernet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ethernet.cc.o
.PHONY : src/protocols/ethernet.cc.o

src/protocols/ethernet.i: src/protocols/ethernet.cc.i
.PHONY : src/protocols/ethernet.i

# target to preprocess a source file
src/protocols/ethernet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ethernet.cc.i
.PHONY : src/protocols/ethernet.cc.i

src/protocols/ethernet.s: src/protocols/ethernet.cc.s
.PHONY : src/protocols/ethernet.s

# target to generate assembly for a file
src/protocols/ethernet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ethernet.cc.s
.PHONY : src/protocols/ethernet.cc.s

src/protocols/ip.o: src/protocols/ip.cc.o
.PHONY : src/protocols/ip.o

# target to build an object file
src/protocols/ip.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ip.cc.o
.PHONY : src/protocols/ip.cc.o

src/protocols/ip.i: src/protocols/ip.cc.i
.PHONY : src/protocols/ip.i

# target to preprocess a source file
src/protocols/ip.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ip.cc.i
.PHONY : src/protocols/ip.cc.i

src/protocols/ip.s: src/protocols/ip.cc.s
.PHONY : src/protocols/ip.s

# target to generate assembly for a file
src/protocols/ip.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/ip.cc.s
.PHONY : src/protocols/ip.cc.s

src/protocols/tcp.o: src/protocols/tcp.cc.o
.PHONY : src/protocols/tcp.o

# target to build an object file
src/protocols/tcp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/tcp.cc.o
.PHONY : src/protocols/tcp.cc.o

src/protocols/tcp.i: src/protocols/tcp.cc.i
.PHONY : src/protocols/tcp.i

# target to preprocess a source file
src/protocols/tcp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/tcp.cc.i
.PHONY : src/protocols/tcp.cc.i

src/protocols/tcp.s: src/protocols/tcp.cc.s
.PHONY : src/protocols/tcp.s

# target to generate assembly for a file
src/protocols/tcp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/tcp.cc.s
.PHONY : src/protocols/tcp.cc.s

src/protocols/udp.o: src/protocols/udp.cc.o
.PHONY : src/protocols/udp.o

# target to build an object file
src/protocols/udp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/udp.cc.o
.PHONY : src/protocols/udp.cc.o

src/protocols/udp.i: src/protocols/udp.cc.i
.PHONY : src/protocols/udp.i

# target to preprocess a source file
src/protocols/udp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/udp.cc.i
.PHONY : src/protocols/udp.cc.i

src/protocols/udp.s: src/protocols/udp.cc.s
.PHONY : src/protocols/udp.s

# target to generate assembly for a file
src/protocols/udp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/protocols/udp.cc.s
.PHONY : src/protocols/udp.cc.s

src/visitors/packet_printer.o: src/visitors/packet_printer.cc.o
.PHONY : src/visitors/packet_printer.o

# target to build an object file
src/visitors/packet_printer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/visitors/packet_printer.cc.o
.PHONY : src/visitors/packet_printer.cc.o

src/visitors/packet_printer.i: src/visitors/packet_printer.cc.i
.PHONY : src/visitors/packet_printer.i

# target to preprocess a source file
src/visitors/packet_printer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/visitors/packet_printer.cc.i
.PHONY : src/visitors/packet_printer.cc.i

src/visitors/packet_printer.s: src/visitors/packet_printer.cc.s
.PHONY : src/visitors/packet_printer.s

# target to generate assembly for a file
src/visitors/packet_printer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reki.dir/build.make CMakeFiles/reki.dir/src/visitors/packet_printer.cc.s
.PHONY : src/visitors/packet_printer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... reki"
	@echo "... soci_core"
	@echo "... soci_core_static"
	@echo "... soci_empty"
	@echo "... soci_empty_static"
	@echo "... soci_empty_test"
	@echo "... soci_empty_test_static"
	@echo "... soci_sqlite3"
	@echo "... soci_sqlite3_static"
	@echo "... soci_sqlite3_test"
	@echo "... soci_sqlite3_test_static"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/packet_stream.o"
	@echo "... src/packet_stream.i"
	@echo "... src/packet_stream.s"
	@echo "... src/protocols/arp.o"
	@echo "... src/protocols/arp.i"
	@echo "... src/protocols/arp.s"
	@echo "... src/protocols/ethernet.o"
	@echo "... src/protocols/ethernet.i"
	@echo "... src/protocols/ethernet.s"
	@echo "... src/protocols/ip.o"
	@echo "... src/protocols/ip.i"
	@echo "... src/protocols/ip.s"
	@echo "... src/protocols/tcp.o"
	@echo "... src/protocols/tcp.i"
	@echo "... src/protocols/tcp.s"
	@echo "... src/protocols/udp.o"
	@echo "... src/protocols/udp.i"
	@echo "... src/protocols/udp.s"
	@echo "... src/visitors/packet_printer.o"
	@echo "... src/visitors/packet_printer.i"
	@echo "... src/visitors/packet_printer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

